config/routes.rb
require "sidekiq/web"

Revily::Application.routes.draw do
  use_doorkeeper
  mount ::Sidekiq::Web => "/sidekiq"
  
  concern :eventable do
    resources :events, only: [ :index ]
  end

  concern :enableable do
    member do
      put "enable"
      put "disable"
    end
  end

  scope module: :integration do
    put "trigger"     => "provider#trigger"
    put "acknowledge" => "provider#acknowledge"
    put "resolve"     => "provider#resolve"

    scope "sms", as: "sms" do
      post ""         => "sms#index"
      post "callback" => "sms#callback"
      post "fallback" => "sms#fallback"
    end

    scope "voice", as: "voice" do
      post ""         => "voice#index"
      post "receive"  => "voice#receive"
      get  "hangup"   => "voice#hangup"
      post "callback" => "voice#callback"
      post "fallback" => "voice#fallback"
    end

    scope "mail", as: "mail" do
      post ""            => "mail#receive"
      post "cloudmailin" => "mail#cloudmailin"
      post "mandrill"    => "mail#mandrill"
      post "postmark"    => "mail#postmark"
      post "sendgrid"    => "mail#sendgrid"
    end
  end

  scope :api, as: :api do
    scope module: :v1, defaults: { format: :json }, constraints: Revily::ApiConstraints.new(version: 1, default: true) do
      get ""   => "root#index"
      get "me" => "root#me"

      resource :registrations, only: [ :show, :create ]
      resource :sessions, only: [ :new, :create, :destroy ]

      resources :services do
        concerns :eventable, :enableable
        resources :incidents, only: [ :index, :new, :create ]
      end

      resources :incidents, only: [ :index, :show, :update, :destroy ] do
        concerns :eventable
        member do
          put "acknowledge"
          put "resolve"
          put "trigger"
          put "escalate"
        end
      end

      resources :policies do
        concerns :eventable
        resources :policy_rules, only: [ :index, :show, :new, :create ] do
          collection do
            post :sort
          end
        end
      end

      resources :policy_rules, except: [ :index, :new, :create ] do
        concerns :eventable
      end

      resources :schedules do
        concerns :eventable
        resources :schedule_layers, path: :layers, as: :layers
        resources :schedule_layers, only: [ :index, :new, :create ]

        get "policy_rules"
        get "users"
        get "on_call"
      end

      resources :schedule_layers, except: [ :index, :new, :create ] do
        resources :events, only: [ :index, :show ]
      end

      resources :users do
        concerns :eventable
        resources :contacts
      end

      resources :contacts, except: [ :new, :create] do
        concerns :eventable
      end

      resources :hooks do
        concerns :enableable
      end
      resources :events, only: [ :index, :show ]
      resources :tokens

    end
  end

  # scope module: :web do
  #   resources :events, only: [ :index, :show ]
  #   resources :hooks, except: [ :new, :edit ]
  #   resources :policies, except: [ :new, :edit ] do
  #     resources :policy_rules, only: [ :create, :update, :destroy ]
  #   end
  #   resources :schedules, except: [ :new, :edit ] do
  #     resources :schedule_layers, only: [ :create, :update, :destroy ]
  #   end
  #   resources :services, except: [ :new, :edit ] do
  #     resources :incidents, only: [ :index, :show ]
  #   end
  #   resources :incidents, only: [ :index ]
  #   resources :users, except: [ :new, :edit ] do
  #     resources :contacts, only: [ :create, :update, :destroy ]
  #   end
  #   resource :confirmations, only: [ :show ]
  # end

  # resource :registrations, only: [ :show, :create ]
  # resource :sessions, only: [ :new, :create, :destroy ]

  # get   "sign_up"  => "registrations#new"
  # post  "sign_up"  => "registrations#create"
  # get   "sign_in"  => "sessions#new"
  # post  "sign_in"  => "sessions#create"
  # match "sign_out" => "sessions#destroy", via: [ :get, :delete ]
  root to: "dashboard#index"
  get "" => "dashboard#index", as: :dashboard
  get "*path" => "dashboard#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
end

app/controllers/integration/application_controller.rb
class Integration::ApplicationController < ActionController::Base
  include Authentication

  respond_to :json

  rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError do |exception|
    render json: { error: "not found" }, status: :not_found
  end
end

app/controllers/v1/application_controller.rb
class V1::ApplicationController < ActionController::Base
  include Authentication

  respond_to :json
  # protect_from_forgery with: :null_session
  # skip_before_action :verify_authenticity_token, 
    # if: ->(c) { c.request.format == "application/json" }
  
  rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError do |exception|
    render json: { error: "not found" }, status: :not_found
  end

  protected

  def query_params
    @query_params ||= request.query_parameters.inject({}) do |res, (key, value)|
      res[key] = value.is_a?(String) ? value.strip.split(",") : value
      res
    end
  end

  def expand_params
    @expand_params ||= (params[:expand]) ? params[:expand].split(",") : []
  end

end

app/views/application/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= msg %>
  <% end %>
<% end %>

app/views/application/_footer.html.erb
<footer id="footer">
  <div class="container">
    <nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
      <p>Copyright &copy; 2013, Applied Awesome LLC.</p>
    </nav>
  </div>
</div>

app/views/application/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Revily", "/", :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Incidents", incidents_path %></li>
        <li><%= link_to "Services", services_path %></li>
        <li><%= link_to "Policies", policies_path %></li>
        <li><%= link_to "Schedules", schedules_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Events", events_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-cog"></span>
          </a>
          <ul class="dropdown-menu">
            <%- if current_user %>
              <li><a href="/settings">Settings</a></li>
              <li><%= link_to "Sign out", sign_out_path, method: :delete %></li>
            <%- else -%>
              <li><%= link_to "Sign in", sign_in_path %></li>
              <li><%= link_to "Sign up", "#" %></li>
            <%- end -%>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/application/_sidebar.html.erb
<ul class="nav nav-stacked">
  <li><%= link_to "Incidents", incidents_path %></li>
  <li><%= link_to "Services", services_path %></li>
  <li><%= link_to "Policies", policies_path %></li>
  <li><%= link_to "Schedules", schedules_path %></li>
  <li><%= link_to "Users", users_path %></li>
  <li><%= link_to "Events", events_path %></li>
</ul>